export const TASK_ACTIONS = {
  ADD_TASK: "ADD_TASK",
  CHANGE_STATUS: "CHANGE_STATUS",
  REMOVE_TASK: "REMOVE_TASK",
  SET_TASK_FROM_MEMORY: "SET_TASK_FROM_MEMORY",
  CHANGE_FILTER: "CHANGE_FILTER",
};
